import type { Metadata } from 'next';

import { Providers } from '@/providers';
import '@/styles/globals.css';
import { appConfig } from '@/config/app.config';
import { HeaderLayout } from '@components/layout/header';
import { ReactNode } from 'react';
import { TAppRequestParams } from '@/types/request.types';
import { fontClassNames } from '@/config/fonts.config';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export async function generateStaticParams() {
  return appConfig.supportedLocales;
}

export default async function RootLayout({ children, params }: Readonly<{ children: ReactNode; params: Promise<TAppRequestParams> }>) {
  const { locale } = await params;

  return (
    <html suppressHydrationWarning lang={locale}>
      <body className={fontClassNames()}>
        <Providers>
          <HeaderLayout />
          {children}
        </Providers>
      </body>
    </html>
  );
}
